apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-b-deployment
  labels:
    app: node-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-b-app
  template:
    metadata:
      labels:
        app: node-b-app
    spec:
      containers:
      - name: node-b-container
        imagePullPolicy: Never
        image: node-b
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: node-b-service
spec:
  selector:
    app: node-b-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
