apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-b-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-b
  template:
    metadata:
      labels:
        app: website-b
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80