apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-a-deployment
  labels:
    app: node-a-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-a-app
  template:
    metadata:
      labels:
        app: node-a-app
    spec:
      containers:
      - name: node-a-container
        imagePullPolicy: Never
        image: node-a
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: node-a-service
spec:
  selector:
    app: node-a-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: node-a-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: cluster.k8s
    http:
      paths:
      - path: /node-a
        backend:
          serviceName: node-a-service
          servicePort: 80